### ISSUE TITLE
Extra features to add soon

### ISSUE THREAD

**Issue by RepComm** [RepComm/exponent-ts#15]
Built in basic components:
- Style
- Text (span)

Built in style constant for `body` tag that can be added.
`const EXPONENT_BODY_STYLES;`
```css
body {
  /*needed to make the page fit the window*/
  top: 0;
  left: 0;
  width: 100vw;
  height: 100vh;
  
  /**Needed to make the page not offset in the window)*/
  margin: 0;
  padding: 0;
  
  /*needed for proper use of components*/
  display: flex;

  /*needed to make the page not scroll from bad default browser css behavior*/
  overflow: hidden;
}
```
